window.Engine = {
  init: (...args) => window.EngineCore.init(...args),
  resize: (...args) => window.EngineCore.resize(...args),
  render: (...args) => window.EngineCore.render(...args),

  buildDungeon: (...args) => window.EngineDungeonRenderer.buildDungeon(...args),
  buildDungeonChunked: (...args) => window.EngineDungeonRenderer.buildDungeonChunked(...args),
  clearDungeon: (...args) => window.EngineDungeonRenderer.clearDungeon(...args),

  buildPlayerMesh: (...args) => window.EngineEntitiesRenderer.buildPlayerMesh(...args),
  updatePlayer: (...args) => window.EngineEntitiesRenderer.updatePlayer(...args),
  updatePlayerEquipment: (...args) => window.EngineEntitiesRenderer.updatePlayerEquipment(...args),
  triggerSwing: (...args) => window.EngineEntitiesRenderer.triggerSwing(...args),
  buildEnemyMesh: (...args) => window.EngineEntitiesRenderer.buildEnemyMesh(...args),
  buildEnemies: (...args) => window.EngineEntitiesRenderer.buildEnemies(...args),
  updateEnemies: (...args) => window.EngineEntitiesRenderer.updateEnemies(...args),
  updateEnemyHpBar: (...args) => window.EngineEntitiesRenderer.updateEnemyHpBar(...args),
  removeEnemyMesh: (...args) => window.EngineEntitiesRenderer.removeEnemyMesh(...args),
  updateEnemyAnimations: (...args) => window.EngineEntitiesRenderer.updateEnemyAnimations(...args),

  buildExitPortal: (...args) => window.EngineInteractables.buildExitPortal(...args),
  removeExitPortal: (...args) => window.EngineInteractables.removeExitPortal(...args),
  revealExitPortal: (...args) => window.EngineInteractables.revealExitPortal(...args),
  buildArrivalPortal: (...args) => window.EngineInteractables.buildArrivalPortal(...args),
  removeArrivalPortal: (...args) => window.EngineInteractables.removeArrivalPortal(...args),
  openBossDoor: (...args) => window.EngineInteractables.openBossDoor(...args),
  updateDoorPrompt: (...args) => window.EngineInteractables.updateDoorPrompt(...args),
  startStairDescent: (...args) => window.EngineInteractables.startStairDescent(...args),
  tickStairDescent: (...args) => window.EngineInteractables.tickStairDescent(...args),
  updateChests: (...args) => window.EngineInteractables.updateChests(...args),
  updateTorches: (...args) => window.EngineInteractables.updateTorches(...args),
  updatePortals: (...args) => window.EngineInteractables.updatePortals(...args),
  updateChestPrompt: (...args) => window.EngineInteractables.updateChestPrompt(...args),
  updateTorchPrompt: (...args) => window.EngineInteractables.updateTorchPrompt(...args),
  updateStairPrompt: (...args) => window.EngineInteractables.updateStairPrompt(...args),
  startChestOpenAnimation: (...args) => window.EngineInteractables.startChestOpenAnimation(...args),
  getChestAnim: (...args) => window.EngineInteractables.getChestAnim(...args),
  toggleNearbyWallTorch: (...args) => window.EngineInteractables.toggleNearbyWallTorch(...args),

  spawnParticles: (...args) => window.EngineEffects.spawnParticles(...args),
  spawnBolt: (...args) => window.EngineEffects.spawnBolt(...args),
  fireBolt: (...args) => window.EngineEffects.fireBolt(...args),
  updateParticles: (...args) => window.EngineEffects.updateParticles(...args),
  updateBolts: (...args) => window.EngineEffects.updateBolts(...args),
  updateTorchFlicker: (...args) => window.EngineLighting.updateTorchFlicker(...args),
  updateLights: (...args) => window.EngineLighting.updateLights(...args),
  snapLanternsToPlayer: (...args) => window.EngineCore.snapLanternsToPlayer(...args),
  clearEffects: (...args) => window.EngineEffects.clearEffects(...args),

  initSound: (...args) => window.EngineSound.init(...args),
  playSound: (...args) => window.EngineSound.play(...args),
  footstep: (...args) => window.EngineSound.footstep(...args),
  registerFootstepMaterial: (...args) => window.EngineSound.registerFootstepMaterial(...args),
  stopAllSounds: (...args) => window.EngineSound.stopAll(...args),
  startAmbient: (...args) => window.EngineSound.startAmbient(...args),
  stopAmbient: (...args) => window.EngineSound.stopAmbient(...args),

  flashPlayer: (...args) => window.EngineCore.flashPlayer(...args),
  clearDynamic: (...args) => window.EngineCore.clearDynamic(...args),
  spawnDamageNumber: (...args) => window.EngineCore.spawnDamageNumber(...args),
  updateDamageNumbers: (...args) => window.EngineCore.updateDamageNumbers(...args),
  reregisterLights: (...args) => window.EngineCore.reregisterLights(...args),
  stashDungeonState: (...args) => window.EngineCore.stashDungeonState(...args),
  installDungeonState: (...args) => window.EngineCore.installDungeonState(...args),
  updateAimFromMouse: (...args) => window.EngineCore.updateAimFromMouse(...args),
  getAimAngle: (...args) => window.EngineCore.getAimAngle(...args),
  setAimAngleDirect: (...args) => window.EngineCore.setAimAngleDirect(...args),
  setAimAngle(value) {
    window.EngineState.aimAngle = value;
  },
  isPointerLocked: (...args) => window.EngineCore.isPointerLocked(...args),

  get chestMeshes() { return window.EngineCore.chestMeshes; },
  get scene() { return window.EngineCore.scene; },
  get camera() { return window.EngineCore.camera; },
  get renderer() { return window.EngineCore.renderer; },
  get clock() { return window.EngineCore.clock; },
};
